### ISSUE TITLE
Locale handling for es_419

### ISSUE THREAD

**Issue by robotdan** [prime-framework/prime-mvc#4]
Locale handling explodes with a locale such as `es_419`. 

### Related
- https://github.com/FusionAuth/fusionauth-issues/issues/978
- https://issues.apache.org/jira/browse/LANG-1312
- https://github.com/apache/commons-lang/pull/239

**Comment by robotdan** [comment]
Related to https://github.com/FusionAuth/fusionauth-internal-issues/issues/81

**Comment by robfusion** [comment]
Should be fixed with recent Locale changes
